---
- name: Deploying Application in tomcat server ...
  hosts: 192.168.56.17
  become: true
  tasks: 
    - name: Download and deploy artifact on tomact server ...
      get_url: 
         url: http://192.168.56.17:8081/repository/harirepo/com/login/AccountLogin/1.0-SNAPSHOT/AccountLogin-1.0-20200517.100407-1.war
         dest: /var/lib/docker/volumes/tomcat_home/_data
         force: yes 
      
